# Generated by Django 5.2.16 on 2026-07-25 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="catalog_pro_categor_ac86d2_idx",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="is_available",
            new_name="in_stock",
        ),
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Coffee: country (str); intensity 0–13; bitterness/acidity/roast/density 0–5. Machines: dimensions, capsule_format, manufacturer_country (str); pressure_bar (int, бар ≥ 0); power_w (int, Вт ≥ 0). All keys optional.",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Previous price for discount display; leave empty if none.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "in_stock"], name="catalog_pro_categor_cafcbf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("product",),
                name="catalog_productimage_one_main_per_product",
            ),
        ),
    ]
